version: "3.5"
volumes:
  event_data: {}
services:
  indexer:
    build:
      context: indexer
      dockerfile: Dockerfile
    volumes:
      - event_data:/app/data
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["/opt/arak/arak"]
    image: indexer.subindexer-gnosis.public.dappnode.eth:0.2.0
  api:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - event_data:/app/data
    depends_on:
      indexer:
        condition: service_started
    environment:
      REDEEMER_PK:
      REDEEM_INTERVAL: 86400
      GNOSIS_RPC_URL: http://execution.gnosis.dncore.dappnode:8545
    ports:
      - 3030:3000
    restart: unless-stopped
    image: api.subindexer-gnosis.public.dappnode.eth:0.2.0
